
clean:
	rm -f ./components/*.h
	rm -f ./expressions/*.h
	rm -f ./pugixml/*.h
	rm -f ./pugixml/*.hpp
	rm -f ./tables/*.h
	rm -f ./utils/*.h
	rm -f ./variables/*.h

	rm -f ./components/*.a
	rm -f ./expressions/*.a
	rm -f ./pugixml/*.a
	rm -f ./tables/*.a
	rm -f ./utils/*.a
	rm -f ./variables/*.a
	rm -f *.out
