
clean:
	rm -f ./components/*.h
	rm -f ./expressions/*.h
	rm -f ./gpio/*.h
	rm -f ./xmlparser/*.h
	rm -f ./xmlparser/*.hpp
	rm -f ./tables/*.h
	rm -f ./utils/*.h
	rm -f ./variables/*.h

	rm -f ./components/*.a
	rm -f ./expressions/*.a
	rm -f ./gpio/*.a
	rm -f ./xmlparser/*.a
	rm -f ./tables/*.a
	rm -f ./utils/*.a
	rm -f ./variables/*.a
	rm -f *.out
