
clean:
	rm -f ./components/*.h
	rm -f ./components/expressions/*.h
	rm -f ./components/variables/*.h
	rm -f ./pugixml/*.h
	rm -f ./pugixml/*.hpp
	rm -f ./utils/*.h
	rm -f ./components/*.a
	rm -f ./components/expressions/*.a
	rm -f ./components/variables/*.a
	rm -f ./pugixml/*.a
	rm -f ./utils/*.a
	rm -f *.out